//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petsmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinShop
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string FacebookURL { get; set; }
        public string GoogleURL { get; set; }
        public string GioiThieu { get; set; }
    }
}
